export const INFURA_KEY="1b4c44fdf5a0404b91ee1a85db0aed9a";
// export const backendURL="https://data.mongodb-api.com/app/data-rfucc/endpoint/data/v1";
export const backendURL="https://admin.givestation.org";

export const Category = [
    "See All",
   'Defi',
    'Education',
    'Blockchain',
    'Fintech',
    'Research',
    'Nutrition',
    'Art-culture',
    'Agriculture',
    'Air',
    'Biodiversity' ,
    'Climate',
    'Community',
    'Food',
    'Non-profit',
    'Housing',
    'Technology',
    'Research',
    "Nutrition",
    'Employment',
    'Energy',
    "Finanace",
    "Health",
    "Infrastructure",
    "Pollution",
    "Real-estate",
    "Waste",
    "Water",
    "Web3",
    "Music",
    "Nft",
    "Event",
    "Space",
    "Other",
];